//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCAutomaticSurveys.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\psychfile\\psych$\\psych-lab-gfong\\SMG\\Access\\Reports\\Automatic Surveys\\")]
        public string AutoSurveysFolder {
            get {
                return ((string)(this["AutoSurveysFolder"]));
            }
            set {
                this["AutoSurveysFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\users\\Automatic Surveys Test\\")]
        public string AutoSurveysFolderTest {
            get {
                return ((string)(this["AutoSurveysFolderTest"]));
            }
            set {
                this["AutoSurveysFolderTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\psychfile\\psych$\\psych-lab-gfong\\SMG\\Access\\Reports\\Automatic Surveys\\With Filt" +
            "ers\\")]
        public string AutoSurveysFolderWithFilters {
            get {
                return ((string)(this["AutoSurveysFolderWithFilters"]));
            }
            set {
                this["AutoSurveysFolderWithFilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\users\\Automatic Surveys Test\\With Filters\\")]
        public string AutoSurveysFolderWithFiltersTest {
            get {
                return ((string)(this["AutoSurveysFolderWithFiltersTest"]));
            }
            set {
                this["AutoSurveysFolderWithFiltersTest"] = value;
            }
        }
    }
}
